### ISSUE TITLE
8.7.19 compatibility

### ISSUE THREAD

**Issue by instruccionesaldorso** [sirdiego/importr#17]
Could the TYPO3 dependency be increased safely from 8.1.99 to 8.7.19?

**Comment by sirdiego** [comment]
Hey @instruccionesaldorso,

thanks for asking. I'll give that one a try and let you know!

**Comment by instruccionesaldorso** [comment]
@sirdiego Could you check it against latest version 8.7.22?
We would like to continue using your extension, it is the only one not compatible in our 8.7 TYPO3 instance.

**Comment by sirdiego** [comment]
Hi @instruccionesaldorso,

thanks for reminding me. There is a 8.7 compatible Version installable via composer. So 2.0.6 should work!

I'll try to update my build/testing configuration so that I can push a last version to TER.

**Comment by instruccionesaldorso** [comment]
Thank you very much, @sirdiego !
Working like a charm!
