### ISSUE TITLE
compat_version() deprecated in TYPO3 v9 und v.10

### ISSUE THREAD

**Issue by aDrygala** [sirdiego/importr#25]
The v.3.0.0 an v.4.0.0 uses the deprecated TYPO3 version check in Classes/Domain/Model/Strategy.php

```php
 if (GeneralUtility::compat_version('8.7')) {
   $service = new LinkService();
   $data = $service->resolveByStringRepresentation($path);
   if ($data['file'] instanceof FileInterface) {
      return $data['file']->getForLocalProcessing(false);
   }
 }
```
**Error**
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::compat_version() | Error thrown in file /app/docroot/typo3conf/ext/importr/Classes/Domain/Model/Strategy.php in line 183. Requested URL: http://foo.bar/typo3/index.php?route=%%2Fsystem%%2FtxschedulerM1%%2F&token=--AnonymizedToken--&tx_scheduler[execute][]=15`

TYPO3 Version: 9.5.23
PHP: 7.4

**Comment by sirdiego** [comment]
@florianPat fixed this for v10 in #26
