### ISSUE TITLE
Release a v10 Version

### ISSUE THREAD

**Issue by lochmueller** [sirdiego/importr#31]
Hey @sirdiego ,

do you push a v10 compatible release to TER? Could I help you with the GitHab actions, that push the releases to TER automatocially? Checkout this action: https://github.com/lochmueller/language_detection/blob/main/.github/workflows/Release.yml

Regards,
Tim

**Comment by sirdiego** [comment]
Hi @lochmueller,

I have not pushed to TER since the Travis shutdown I guess. I'll take a look!

Thanks!

**Comment by sirdiego** [comment]
Hi @lochmueller,

there is a new version 5.0.0 now. It is also published to the TER. Thanks for your input.
